# Generated by Django 2.2.5 on 2020-01-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_table2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2',
            name='eng',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table2',
            name='kor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table2',
            name='math',
            field=models.IntegerField(null=True),
        ),
    ]
